# Generated by Django 5.0.7 on 2024-07-28 08:00

import qrapp.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visite_time', models.DateTimeField(blank=True, null=True)),
                ('return_time', models.DateTimeField(blank=True, null=True)),
                ('person_name', models.CharField(max_length=100, null=True)),
                ('phone_no', qrapp.models.PhoneNumberField(max_length=20, null=True, region='US')),
                ('purpose_of_visit', models.TextField(blank=True, null=True)),
                ('visit_id', models.CharField(default=uuid.uuid4, editable=False, max_length=30, unique=True)),
            ],
        ),
    ]
