# Generated by Django 5.0.7 on 2024-08-06 14:19

import qrapp.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrapp', '0002_failedloginattempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='phone_no',
            field=qrapp.models.PhoneNumberField(max_length=15, null=True, region='IN'),
        ),
    ]
