# Generated by Django 5.0.7 on 2024-08-06 14:27

import qrapp.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrapp', '0004_alter_register_phone_no_alter_register_visit_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='phone_no',
            field=qrapp.models.PhoneNumberField(max_length=15, null=True, region='IN'),
        ),
    ]
