# Generated by Django 5.0.7 on 2024-08-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrapp', '0005_alter_register_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='visite_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
